//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class New_Scene : TypedScene
    {
        
        private const string GUID = "3417602231161af48b9682e519590d2f";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
        
        public static void Load(ExampleSceneLoadModel argument)
        {
            LoadScene(GUID, argument);
        }
        
        public static void Load(int argument)
        {
            LoadScene(GUID, argument);
        }
    }
}
