//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class SampleScene : TypedScene
    {
        
        private const string GUID = "9fc0d4010bbf28b4594072e72b8655ab";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
