//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    
    
    public class Test : TypedScene
    {
        
        private const string GUID = "295beaa3974fd824f870040b5be4da5b";
        
        public static void Load()
        {
            LoadScene(GUID);
        }
    }
}
