//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScene
{
    
    
    public class New_Scene__23 : TypedScene
    {
        
        private const string _path = "Assets/Plugins/TypedScenes/Samples/New Scene @23.unity";
        
        public static void Load()
        {
            LoadScene(_path);
        }
    }
}
