//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScene
{
    public class TestScene2 : TypedScene
    {
        private const string _path = "Assets/Plugins/TypedScenes/Samples/TestScene2.unity";

        public static void Load()
        {
            LoadScene(_path);
        }
    }
}
